<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_email</name>
   <tag></tag>
   <elementGuidId>a3eff5f0-2677-4e15-9cf3-b481c662c777</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[type='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e9df5c7-e427-41db-a6ac-4dbf16b47c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ca6ef7b3-f025-481a-8296-bbcbf5a69551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[type='email']</value>
      <webElementGuid>55cb3450-c669-41da-b3dd-39a3b478fe09</webElementGuid>
   </webElementProperties>
</WebElementEntity>
