<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_name</name>
   <tag></tag>
   <elementGuidId>de59755d-7446-4784-9229-064922913d6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eab42d49-f0a0-476b-b9c9-efa105e58b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>206ce9fd-f27e-4006-acf6-e3b65b293dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[type='text']</value>
      <webElementGuid>c3d4eb8d-13a2-4c9f-a15c-56fab9636ec7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
